"""Vertex AI RAG Engine クライアント

Vertex AI RAG Engineを使用して、
行政事業レビューデータに対するRAGベースの回答生成を実行するクライアントを提供します。
"""

import logging
import os
from typing import Any
import vertexai
from vertexai.generative_models import GenerativeModel, Tool
from vertexai import rag
from tenacity import retry, stop_after_attempt, wait_exponential

# Code Executionツールをインポート
try:
    from vertexai.preview.generative_models import grounding
except ImportError:
    grounding = None

# ロガーの設定
logger = logging.getLogger(__name__)


class VertexAIRAGClient:
    """Vertex AI RAG Engine クライアント"""

    def __init__(
        self,
        project_id: str,
        location: str,
        rag_corpus_resource_name: str,
        model_name: str = "gemini-2.5-flash",
        temperature: float = 0.7,
        max_output_tokens: int = 2048,
        top_k: int = 5,
    ):
        """
        Args:
            project_id: GCPプロジェクトID
            location: リージョン（例: us-central1）
            rag_corpus_resource_name: RAG Corpusのリソース名
            model_name: 使用するモデル名
            temperature: 生成の温度パラメータ
            max_output_tokens: 最大出力トークン数
            top_k: RAG検索の上位K件
        """
        self.project_id = project_id
        self.location = location  # RAG corpus のロケーション（例: us-east4）
        self.rag_corpus_resource_name = rag_corpus_resource_name
        self.model_name = model_name
        self.temperature = temperature
        self.max_output_tokens = max_output_tokens
        self.top_k = top_k

        # Vertex AIの初期化
        # モデルのロケーション（例: us-central1）を環境変数で上書き可能
        model_location = os.getenv("MODEL_LOCATION") or location
        vertexai.init(project=project_id, location=model_location)

        # RAGツールの設定
        rag_retrieval_tool = Tool.from_retrieval(
            retrieval=rag.Retrieval(
                source=rag.VertexRagStore(
                    rag_resources=[
                        rag.RagResource(rag_corpus=rag_corpus_resource_name)
                    ],
                    rag_retrieval_config=rag.RagRetrievalConfig(
                        top_k=top_k,
                    ),
                ),
            )
        )

        # Code Executionツールの設定
        code_execution_tool = Tool.from_code_execution()

        # GenerativeModelの初期化（RAG + Code Execution）
        self.model = GenerativeModel(
            model_name=model_name,
            tools=[rag_retrieval_tool, code_execution_tool],
        )

        logger.info(
            f"VertexAIRAGClient initialized: "
            f"project={project_id}, model_location={model_location}, rag_location={location}, "
            f"rag_corpus={rag_corpus_resource_name}, model={model_name}, top_k={top_k}, "
            f"code_execution=enabled"
        )

    @retry(
        stop=stop_after_attempt(3),
        wait=wait_exponential(multiplier=1, min=2, max=10)
    )
    def generate_answer(
        self,
        query: str,
    ) -> dict[str, Any]:
        """
        Vertex AI RAG で検索を実行し、回答を生成

        Args:
            query: 質問文

        Returns:
            生成された回答を含む辞書
            {
                "answer": "生成された回答",
                "grounding_metadata": グラウンディングメタデータ（参照元情報）
            }

        Raises:
            VertexAIRAGError: API呼び出しに失敗した場合
        """
        logger.info(f"Vertex AI RAG query started: query='{query}'")

        try:
            # コンテンツの生成
            response = self.model.generate_content(
                query,
                generation_config={
                    "temperature": self.temperature,
                    "max_output_tokens": self.max_output_tokens,
                }
            )

            # 回答テキストの抽出
            answer = response.text if hasattr(response, 'text') and response.text else ""

            # グラウンディングメタデータの抽出
            grounding_metadata = None
            if hasattr(response, 'candidates') and response.candidates:
                candidate = response.candidates[0]
                if hasattr(candidate, 'grounding_metadata'):
                    grounding_metadata = candidate.grounding_metadata

            if not answer:
                logger.warning("No answer generated by Vertex AI RAG")
                answer = "申し訳ございません。該当する情報が見つかりませんでした。"

            logger.info(
                f"RAG query completed: answer_length={len(answer)}"
            )

            return {
                "answer": answer,
                "grounding_metadata": grounding_metadata
            }

        except Exception as e:
            logger.error(f"Vertex AI RAG query failed: {str(e)}", exc_info=True)
            raise VertexAIRAGError(f"Vertex AI RAG query failed: {str(e)}") from e


class VertexAIRAGError(Exception):
    """Vertex AI RAG Engine API呼び出しのエラー"""
    pass
